# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-03 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hearing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pta', models.IntegerField()),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
