# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-03 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hearing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'M'), ('Female', 'F')], max_length=10)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
